// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: blobcast/rollup/v1/blobcast_envelope.proto

package v1

import (
	v1 "github.com/forma-dev/blobcast/pkg/proto/blobcast/storage/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlobcastEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*BlobcastEnvelope_ChunkData
	//	*BlobcastEnvelope_FileManifest
	//	*BlobcastEnvelope_DirectoryManifest
	Payload       isBlobcastEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobcastEnvelope) Reset() {
	*x = BlobcastEnvelope{}
	mi := &file_blobcast_rollup_v1_blobcast_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobcastEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobcastEnvelope) ProtoMessage() {}

func (x *BlobcastEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_blobcast_rollup_v1_blobcast_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobcastEnvelope.ProtoReflect.Descriptor instead.
func (*BlobcastEnvelope) Descriptor() ([]byte, []int) {
	return file_blobcast_rollup_v1_blobcast_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *BlobcastEnvelope) GetPayload() isBlobcastEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BlobcastEnvelope) GetChunkData() *v1.ChunkData {
	if x != nil {
		if x, ok := x.Payload.(*BlobcastEnvelope_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

func (x *BlobcastEnvelope) GetFileManifest() *v1.FileManifest {
	if x != nil {
		if x, ok := x.Payload.(*BlobcastEnvelope_FileManifest); ok {
			return x.FileManifest
		}
	}
	return nil
}

func (x *BlobcastEnvelope) GetDirectoryManifest() *v1.DirectoryManifest {
	if x != nil {
		if x, ok := x.Payload.(*BlobcastEnvelope_DirectoryManifest); ok {
			return x.DirectoryManifest
		}
	}
	return nil
}

type isBlobcastEnvelope_Payload interface {
	isBlobcastEnvelope_Payload()
}

type BlobcastEnvelope_ChunkData struct {
	ChunkData *v1.ChunkData `protobuf:"bytes,1,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

type BlobcastEnvelope_FileManifest struct {
	FileManifest *v1.FileManifest `protobuf:"bytes,2,opt,name=file_manifest,json=fileManifest,proto3,oneof"`
}

type BlobcastEnvelope_DirectoryManifest struct {
	DirectoryManifest *v1.DirectoryManifest `protobuf:"bytes,3,opt,name=directory_manifest,json=directoryManifest,proto3,oneof"`
}

func (*BlobcastEnvelope_ChunkData) isBlobcastEnvelope_Payload() {}

func (*BlobcastEnvelope_FileManifest) isBlobcastEnvelope_Payload() {}

func (*BlobcastEnvelope_DirectoryManifest) isBlobcastEnvelope_Payload() {}

var File_blobcast_rollup_v1_blobcast_envelope_proto protoreflect.FileDescriptor

const file_blobcast_rollup_v1_blobcast_envelope_proto_rawDesc = "" +
	"\n" +
	"*blobcast/rollup/v1/blobcast_envelope.proto\x12\x12blobcast.rollup.v1\x1a$blobcast/storage/v1/chunk_data.proto\x1a'blobcast/storage/v1/file_manifest.proto\x1a,blobcast/storage/v1/directory_manifest.proto\"\x81\x02\n" +
	"\x10BlobcastEnvelope\x12?\n" +
	"\n" +
	"chunk_data\x18\x01 \x01(\v2\x1e.blobcast.storage.v1.ChunkDataH\x00R\tchunkData\x12H\n" +
	"\rfile_manifest\x18\x02 \x01(\v2!.blobcast.storage.v1.FileManifestH\x00R\ffileManifest\x12W\n" +
	"\x12directory_manifest\x18\x03 \x01(\v2&.blobcast.storage.v1.DirectoryManifestH\x00R\x11directoryManifestB\t\n" +
	"\apayloadB<Z:github.com/forma-dev/blobcast/pkg/proto/blobcast/rollup/v1b\x06proto3"

var (
	file_blobcast_rollup_v1_blobcast_envelope_proto_rawDescOnce sync.Once
	file_blobcast_rollup_v1_blobcast_envelope_proto_rawDescData []byte
)

func file_blobcast_rollup_v1_blobcast_envelope_proto_rawDescGZIP() []byte {
	file_blobcast_rollup_v1_blobcast_envelope_proto_rawDescOnce.Do(func() {
		file_blobcast_rollup_v1_blobcast_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blobcast_rollup_v1_blobcast_envelope_proto_rawDesc), len(file_blobcast_rollup_v1_blobcast_envelope_proto_rawDesc)))
	})
	return file_blobcast_rollup_v1_blobcast_envelope_proto_rawDescData
}

var file_blobcast_rollup_v1_blobcast_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_blobcast_rollup_v1_blobcast_envelope_proto_goTypes = []any{
	(*BlobcastEnvelope)(nil),     // 0: blobcast.rollup.v1.BlobcastEnvelope
	(*v1.ChunkData)(nil),         // 1: blobcast.storage.v1.ChunkData
	(*v1.FileManifest)(nil),      // 2: blobcast.storage.v1.FileManifest
	(*v1.DirectoryManifest)(nil), // 3: blobcast.storage.v1.DirectoryManifest
}
var file_blobcast_rollup_v1_blobcast_envelope_proto_depIdxs = []int32{
	1, // 0: blobcast.rollup.v1.BlobcastEnvelope.chunk_data:type_name -> blobcast.storage.v1.ChunkData
	2, // 1: blobcast.rollup.v1.BlobcastEnvelope.file_manifest:type_name -> blobcast.storage.v1.FileManifest
	3, // 2: blobcast.rollup.v1.BlobcastEnvelope.directory_manifest:type_name -> blobcast.storage.v1.DirectoryManifest
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_blobcast_rollup_v1_blobcast_envelope_proto_init() }
func file_blobcast_rollup_v1_blobcast_envelope_proto_init() {
	if File_blobcast_rollup_v1_blobcast_envelope_proto != nil {
		return
	}
	file_blobcast_rollup_v1_blobcast_envelope_proto_msgTypes[0].OneofWrappers = []any{
		(*BlobcastEnvelope_ChunkData)(nil),
		(*BlobcastEnvelope_FileManifest)(nil),
		(*BlobcastEnvelope_DirectoryManifest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blobcast_rollup_v1_blobcast_envelope_proto_rawDesc), len(file_blobcast_rollup_v1_blobcast_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blobcast_rollup_v1_blobcast_envelope_proto_goTypes,
		DependencyIndexes: file_blobcast_rollup_v1_blobcast_envelope_proto_depIdxs,
		MessageInfos:      file_blobcast_rollup_v1_blobcast_envelope_proto_msgTypes,
	}.Build()
	File_blobcast_rollup_v1_blobcast_envelope_proto = out.File
	file_blobcast_rollup_v1_blobcast_envelope_proto_goTypes = nil
	file_blobcast_rollup_v1_blobcast_envelope_proto_depIdxs = nil
}
