// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: blobcast/rollup/v1/block_body.proto

package v1

import (
	v1 "github.com/forma-dev/blobcast/pkg/proto/blobcast/primitives/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dirs          []*v1.BlobIdentifier   `protobuf:"bytes,1,rep,name=dirs,proto3" json:"dirs,omitempty"`
	Files         []*v1.BlobIdentifier   `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	Chunks        []*v1.BlobIdentifier   `protobuf:"bytes,3,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockBody) Reset() {
	*x = BlockBody{}
	mi := &file_blobcast_rollup_v1_block_body_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockBody) ProtoMessage() {}

func (x *BlockBody) ProtoReflect() protoreflect.Message {
	mi := &file_blobcast_rollup_v1_block_body_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockBody.ProtoReflect.Descriptor instead.
func (*BlockBody) Descriptor() ([]byte, []int) {
	return file_blobcast_rollup_v1_block_body_proto_rawDescGZIP(), []int{0}
}

func (x *BlockBody) GetDirs() []*v1.BlobIdentifier {
	if x != nil {
		return x.Dirs
	}
	return nil
}

func (x *BlockBody) GetFiles() []*v1.BlobIdentifier {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *BlockBody) GetChunks() []*v1.BlobIdentifier {
	if x != nil {
		return x.Chunks
	}
	return nil
}

var File_blobcast_rollup_v1_block_body_proto protoreflect.FileDescriptor

const file_blobcast_rollup_v1_block_body_proto_rawDesc = "" +
	"\n" +
	"#blobcast/rollup/v1/block_body.proto\x12\x12blobcast.rollup.v1\x1a,blobcast/primitives/v1/blob_identifier.proto\"\xc5\x01\n" +
	"\tBlockBody\x12:\n" +
	"\x04dirs\x18\x01 \x03(\v2&.blobcast.primitives.v1.BlobIdentifierR\x04dirs\x12<\n" +
	"\x05files\x18\x02 \x03(\v2&.blobcast.primitives.v1.BlobIdentifierR\x05files\x12>\n" +
	"\x06chunks\x18\x03 \x03(\v2&.blobcast.primitives.v1.BlobIdentifierR\x06chunksB<Z:github.com/forma-dev/blobcast/pkg/proto/blobcast/rollup/v1b\x06proto3"

var (
	file_blobcast_rollup_v1_block_body_proto_rawDescOnce sync.Once
	file_blobcast_rollup_v1_block_body_proto_rawDescData []byte
)

func file_blobcast_rollup_v1_block_body_proto_rawDescGZIP() []byte {
	file_blobcast_rollup_v1_block_body_proto_rawDescOnce.Do(func() {
		file_blobcast_rollup_v1_block_body_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blobcast_rollup_v1_block_body_proto_rawDesc), len(file_blobcast_rollup_v1_block_body_proto_rawDesc)))
	})
	return file_blobcast_rollup_v1_block_body_proto_rawDescData
}

var file_blobcast_rollup_v1_block_body_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_blobcast_rollup_v1_block_body_proto_goTypes = []any{
	(*BlockBody)(nil),         // 0: blobcast.rollup.v1.BlockBody
	(*v1.BlobIdentifier)(nil), // 1: blobcast.primitives.v1.BlobIdentifier
}
var file_blobcast_rollup_v1_block_body_proto_depIdxs = []int32{
	1, // 0: blobcast.rollup.v1.BlockBody.dirs:type_name -> blobcast.primitives.v1.BlobIdentifier
	1, // 1: blobcast.rollup.v1.BlockBody.files:type_name -> blobcast.primitives.v1.BlobIdentifier
	1, // 2: blobcast.rollup.v1.BlockBody.chunks:type_name -> blobcast.primitives.v1.BlobIdentifier
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_blobcast_rollup_v1_block_body_proto_init() }
func file_blobcast_rollup_v1_block_body_proto_init() {
	if File_blobcast_rollup_v1_block_body_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blobcast_rollup_v1_block_body_proto_rawDesc), len(file_blobcast_rollup_v1_block_body_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blobcast_rollup_v1_block_body_proto_goTypes,
		DependencyIndexes: file_blobcast_rollup_v1_block_body_proto_depIdxs,
		MessageInfos:      file_blobcast_rollup_v1_block_body_proto_msgTypes,
	}.Build()
	File_blobcast_rollup_v1_block_body_proto = out.File
	file_blobcast_rollup_v1_block_body_proto_goTypes = nil
	file_blobcast_rollup_v1_block_body_proto_depIdxs = nil
}
