// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: blobcast/rollup/v1/block_header.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockHeader struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Version             uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ChainId             string                 `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Height              uint64                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	CelestiaBlockHeight uint64                 `protobuf:"varint,4,opt,name=celestia_block_height,json=celestiaBlockHeight,proto3" json:"celestia_block_height,omitempty"`
	Timestamp           *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ParentHash          []byte                 `protobuf:"bytes,6,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"` // bytes32
	DirsRoot            []byte                 `protobuf:"bytes,7,opt,name=dirs_root,json=dirsRoot,proto3" json:"dirs_root,omitempty"`       // bytes32
	FilesRoot           []byte                 `protobuf:"bytes,8,opt,name=files_root,json=filesRoot,proto3" json:"files_root,omitempty"`    // bytes32
	ChunksRoot          []byte                 `protobuf:"bytes,9,opt,name=chunks_root,json=chunksRoot,proto3" json:"chunks_root,omitempty"` // bytes32
	StateRoot           []byte                 `protobuf:"bytes,10,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`   // bytes32
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BlockHeader) Reset() {
	*x = BlockHeader{}
	mi := &file_blobcast_rollup_v1_block_header_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeader) ProtoMessage() {}

func (x *BlockHeader) ProtoReflect() protoreflect.Message {
	mi := &file_blobcast_rollup_v1_block_header_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeader.ProtoReflect.Descriptor instead.
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return file_blobcast_rollup_v1_block_header_proto_rawDescGZIP(), []int{0}
}

func (x *BlockHeader) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BlockHeader) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *BlockHeader) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockHeader) GetCelestiaBlockHeight() uint64 {
	if x != nil {
		return x.CelestiaBlockHeight
	}
	return 0
}

func (x *BlockHeader) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *BlockHeader) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *BlockHeader) GetDirsRoot() []byte {
	if x != nil {
		return x.DirsRoot
	}
	return nil
}

func (x *BlockHeader) GetFilesRoot() []byte {
	if x != nil {
		return x.FilesRoot
	}
	return nil
}

func (x *BlockHeader) GetChunksRoot() []byte {
	if x != nil {
		return x.ChunksRoot
	}
	return nil
}

func (x *BlockHeader) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

var File_blobcast_rollup_v1_block_header_proto protoreflect.FileDescriptor

const file_blobcast_rollup_v1_block_header_proto_rawDesc = "" +
	"\n" +
	"%blobcast/rollup/v1/block_header.proto\x12\x12blobcast.rollup.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe5\x02\n" +
	"\vBlockHeader\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\tR\achainId\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x04R\x06height\x122\n" +
	"\x15celestia_block_height\x18\x04 \x01(\x04R\x13celestiaBlockHeight\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1f\n" +
	"\vparent_hash\x18\x06 \x01(\fR\n" +
	"parentHash\x12\x1b\n" +
	"\tdirs_root\x18\a \x01(\fR\bdirsRoot\x12\x1d\n" +
	"\n" +
	"files_root\x18\b \x01(\fR\tfilesRoot\x12\x1f\n" +
	"\vchunks_root\x18\t \x01(\fR\n" +
	"chunksRoot\x12\x1d\n" +
	"\n" +
	"state_root\x18\n" +
	" \x01(\fR\tstateRootB<Z:github.com/forma-dev/blobcast/pkg/proto/blobcast/rollup/v1b\x06proto3"

var (
	file_blobcast_rollup_v1_block_header_proto_rawDescOnce sync.Once
	file_blobcast_rollup_v1_block_header_proto_rawDescData []byte
)

func file_blobcast_rollup_v1_block_header_proto_rawDescGZIP() []byte {
	file_blobcast_rollup_v1_block_header_proto_rawDescOnce.Do(func() {
		file_blobcast_rollup_v1_block_header_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blobcast_rollup_v1_block_header_proto_rawDesc), len(file_blobcast_rollup_v1_block_header_proto_rawDesc)))
	})
	return file_blobcast_rollup_v1_block_header_proto_rawDescData
}

var file_blobcast_rollup_v1_block_header_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_blobcast_rollup_v1_block_header_proto_goTypes = []any{
	(*BlockHeader)(nil),           // 0: blobcast.rollup.v1.BlockHeader
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_blobcast_rollup_v1_block_header_proto_depIdxs = []int32{
	1, // 0: blobcast.rollup.v1.BlockHeader.timestamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_blobcast_rollup_v1_block_header_proto_init() }
func file_blobcast_rollup_v1_block_header_proto_init() {
	if File_blobcast_rollup_v1_block_header_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blobcast_rollup_v1_block_header_proto_rawDesc), len(file_blobcast_rollup_v1_block_header_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blobcast_rollup_v1_block_header_proto_goTypes,
		DependencyIndexes: file_blobcast_rollup_v1_block_header_proto_depIdxs,
		MessageInfos:      file_blobcast_rollup_v1_block_header_proto_msgTypes,
	}.Build()
	File_blobcast_rollup_v1_block_header_proto = out.File
	file_blobcast_rollup_v1_block_header_proto_goTypes = nil
	file_blobcast_rollup_v1_block_header_proto_depIdxs = nil
}
