// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: blobcast/rollup/v1/block.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *BlockHeader           `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body          *BlockBody             `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_blobcast_rollup_v1_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_blobcast_rollup_v1_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_blobcast_rollup_v1_block_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetHeader() *BlockHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Block) GetBody() *BlockBody {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_blobcast_rollup_v1_block_proto protoreflect.FileDescriptor

const file_blobcast_rollup_v1_block_proto_rawDesc = "" +
	"\n" +
	"\x1eblobcast/rollup/v1/block.proto\x12\x12blobcast.rollup.v1\x1a%blobcast/rollup/v1/block_header.proto\x1a#blobcast/rollup/v1/block_body.proto\"s\n" +
	"\x05Block\x127\n" +
	"\x06header\x18\x01 \x01(\v2\x1f.blobcast.rollup.v1.BlockHeaderR\x06header\x121\n" +
	"\x04body\x18\x02 \x01(\v2\x1d.blobcast.rollup.v1.BlockBodyR\x04bodyB<Z:github.com/forma-dev/blobcast/pkg/proto/blobcast/rollup/v1b\x06proto3"

var (
	file_blobcast_rollup_v1_block_proto_rawDescOnce sync.Once
	file_blobcast_rollup_v1_block_proto_rawDescData []byte
)

func file_blobcast_rollup_v1_block_proto_rawDescGZIP() []byte {
	file_blobcast_rollup_v1_block_proto_rawDescOnce.Do(func() {
		file_blobcast_rollup_v1_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blobcast_rollup_v1_block_proto_rawDesc), len(file_blobcast_rollup_v1_block_proto_rawDesc)))
	})
	return file_blobcast_rollup_v1_block_proto_rawDescData
}

var file_blobcast_rollup_v1_block_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_blobcast_rollup_v1_block_proto_goTypes = []any{
	(*Block)(nil),       // 0: blobcast.rollup.v1.Block
	(*BlockHeader)(nil), // 1: blobcast.rollup.v1.BlockHeader
	(*BlockBody)(nil),   // 2: blobcast.rollup.v1.BlockBody
}
var file_blobcast_rollup_v1_block_proto_depIdxs = []int32{
	1, // 0: blobcast.rollup.v1.Block.header:type_name -> blobcast.rollup.v1.BlockHeader
	2, // 1: blobcast.rollup.v1.Block.body:type_name -> blobcast.rollup.v1.BlockBody
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_blobcast_rollup_v1_block_proto_init() }
func file_blobcast_rollup_v1_block_proto_init() {
	if File_blobcast_rollup_v1_block_proto != nil {
		return
	}
	file_blobcast_rollup_v1_block_header_proto_init()
	file_blobcast_rollup_v1_block_body_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blobcast_rollup_v1_block_proto_rawDesc), len(file_blobcast_rollup_v1_block_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blobcast_rollup_v1_block_proto_goTypes,
		DependencyIndexes: file_blobcast_rollup_v1_block_proto_depIdxs,
		MessageInfos:      file_blobcast_rollup_v1_block_proto_msgTypes,
	}.Build()
	File_blobcast_rollup_v1_block_proto = out.File
	file_blobcast_rollup_v1_block_proto_goTypes = nil
	file_blobcast_rollup_v1_block_proto_depIdxs = nil
}
