// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: blobcast/rollupapis/v1/subscribe_to_headers_request.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeToHeadersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional start height to begin streaming from
	// If not set or 0, will only stream new headers as they are finalized
	// If set, will first stream historical headers from this height, then continue with new headers
	StartHeight   uint64 `protobuf:"varint,1,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeToHeadersRequest) Reset() {
	*x = SubscribeToHeadersRequest{}
	mi := &file_blobcast_rollupapis_v1_subscribe_to_headers_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeToHeadersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeToHeadersRequest) ProtoMessage() {}

func (x *SubscribeToHeadersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blobcast_rollupapis_v1_subscribe_to_headers_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeToHeadersRequest.ProtoReflect.Descriptor instead.
func (*SubscribeToHeadersRequest) Descriptor() ([]byte, []int) {
	return file_blobcast_rollupapis_v1_subscribe_to_headers_request_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeToHeadersRequest) GetStartHeight() uint64 {
	if x != nil {
		return x.StartHeight
	}
	return 0
}

var File_blobcast_rollupapis_v1_subscribe_to_headers_request_proto protoreflect.FileDescriptor

const file_blobcast_rollupapis_v1_subscribe_to_headers_request_proto_rawDesc = "" +
	"\n" +
	"9blobcast/rollupapis/v1/subscribe_to_headers_request.proto\x12\x16blobcast.rollupapis.v1\">\n" +
	"\x19SubscribeToHeadersRequest\x12!\n" +
	"\fstart_height\x18\x01 \x01(\x04R\vstartHeightB@Z>github.com/forma-dev/blobcast/pkg/proto/blobcast/rollupapis/v1b\x06proto3"

var (
	file_blobcast_rollupapis_v1_subscribe_to_headers_request_proto_rawDescOnce sync.Once
	file_blobcast_rollupapis_v1_subscribe_to_headers_request_proto_rawDescData []byte
)

func file_blobcast_rollupapis_v1_subscribe_to_headers_request_proto_rawDescGZIP() []byte {
	file_blobcast_rollupapis_v1_subscribe_to_headers_request_proto_rawDescOnce.Do(func() {
		file_blobcast_rollupapis_v1_subscribe_to_headers_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blobcast_rollupapis_v1_subscribe_to_headers_request_proto_rawDesc), len(file_blobcast_rollupapis_v1_subscribe_to_headers_request_proto_rawDesc)))
	})
	return file_blobcast_rollupapis_v1_subscribe_to_headers_request_proto_rawDescData
}

var file_blobcast_rollupapis_v1_subscribe_to_headers_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_blobcast_rollupapis_v1_subscribe_to_headers_request_proto_goTypes = []any{
	(*SubscribeToHeadersRequest)(nil), // 0: blobcast.rollupapis.v1.SubscribeToHeadersRequest
}
var file_blobcast_rollupapis_v1_subscribe_to_headers_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blobcast_rollupapis_v1_subscribe_to_headers_request_proto_init() }
func file_blobcast_rollupapis_v1_subscribe_to_headers_request_proto_init() {
	if File_blobcast_rollupapis_v1_subscribe_to_headers_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blobcast_rollupapis_v1_subscribe_to_headers_request_proto_rawDesc), len(file_blobcast_rollupapis_v1_subscribe_to_headers_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blobcast_rollupapis_v1_subscribe_to_headers_request_proto_goTypes,
		DependencyIndexes: file_blobcast_rollupapis_v1_subscribe_to_headers_request_proto_depIdxs,
		MessageInfos:      file_blobcast_rollupapis_v1_subscribe_to_headers_request_proto_msgTypes,
	}.Build()
	File_blobcast_rollupapis_v1_subscribe_to_headers_request_proto = out.File
	file_blobcast_rollupapis_v1_subscribe_to_headers_request_proto_goTypes = nil
	file_blobcast_rollupapis_v1_subscribe_to_headers_request_proto_depIdxs = nil
}
