// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: blobcast/rollupapis/v1/subscribe_to_headers_response.proto

package v1

import (
	v1 "github.com/forma-dev/blobcast/pkg/proto/blobcast/rollup/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeToHeadersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Block header (without body containing chunks/files/dirs)
	// Clients can fetch the full block using GetBlockByHeight or GetBlockByHash
	Header *v1.BlockHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// Block hash for convenience
	Hash          []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeToHeadersResponse) Reset() {
	*x = SubscribeToHeadersResponse{}
	mi := &file_blobcast_rollupapis_v1_subscribe_to_headers_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeToHeadersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeToHeadersResponse) ProtoMessage() {}

func (x *SubscribeToHeadersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blobcast_rollupapis_v1_subscribe_to_headers_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeToHeadersResponse.ProtoReflect.Descriptor instead.
func (*SubscribeToHeadersResponse) Descriptor() ([]byte, []int) {
	return file_blobcast_rollupapis_v1_subscribe_to_headers_response_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeToHeadersResponse) GetHeader() *v1.BlockHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SubscribeToHeadersResponse) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

var File_blobcast_rollupapis_v1_subscribe_to_headers_response_proto protoreflect.FileDescriptor

const file_blobcast_rollupapis_v1_subscribe_to_headers_response_proto_rawDesc = "" +
	"\n" +
	":blobcast/rollupapis/v1/subscribe_to_headers_response.proto\x12\x16blobcast.rollupapis.v1\x1a%blobcast/rollup/v1/block_header.proto\"i\n" +
	"\x1aSubscribeToHeadersResponse\x127\n" +
	"\x06header\x18\x01 \x01(\v2\x1f.blobcast.rollup.v1.BlockHeaderR\x06header\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hashB@Z>github.com/forma-dev/blobcast/pkg/proto/blobcast/rollupapis/v1b\x06proto3"

var (
	file_blobcast_rollupapis_v1_subscribe_to_headers_response_proto_rawDescOnce sync.Once
	file_blobcast_rollupapis_v1_subscribe_to_headers_response_proto_rawDescData []byte
)

func file_blobcast_rollupapis_v1_subscribe_to_headers_response_proto_rawDescGZIP() []byte {
	file_blobcast_rollupapis_v1_subscribe_to_headers_response_proto_rawDescOnce.Do(func() {
		file_blobcast_rollupapis_v1_subscribe_to_headers_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blobcast_rollupapis_v1_subscribe_to_headers_response_proto_rawDesc), len(file_blobcast_rollupapis_v1_subscribe_to_headers_response_proto_rawDesc)))
	})
	return file_blobcast_rollupapis_v1_subscribe_to_headers_response_proto_rawDescData
}

var file_blobcast_rollupapis_v1_subscribe_to_headers_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_blobcast_rollupapis_v1_subscribe_to_headers_response_proto_goTypes = []any{
	(*SubscribeToHeadersResponse)(nil), // 0: blobcast.rollupapis.v1.SubscribeToHeadersResponse
	(*v1.BlockHeader)(nil),             // 1: blobcast.rollup.v1.BlockHeader
}
var file_blobcast_rollupapis_v1_subscribe_to_headers_response_proto_depIdxs = []int32{
	1, // 0: blobcast.rollupapis.v1.SubscribeToHeadersResponse.header:type_name -> blobcast.rollup.v1.BlockHeader
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_blobcast_rollupapis_v1_subscribe_to_headers_response_proto_init() }
func file_blobcast_rollupapis_v1_subscribe_to_headers_response_proto_init() {
	if File_blobcast_rollupapis_v1_subscribe_to_headers_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blobcast_rollupapis_v1_subscribe_to_headers_response_proto_rawDesc), len(file_blobcast_rollupapis_v1_subscribe_to_headers_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blobcast_rollupapis_v1_subscribe_to_headers_response_proto_goTypes,
		DependencyIndexes: file_blobcast_rollupapis_v1_subscribe_to_headers_response_proto_depIdxs,
		MessageInfos:      file_blobcast_rollupapis_v1_subscribe_to_headers_response_proto_msgTypes,
	}.Build()
	File_blobcast_rollupapis_v1_subscribe_to_headers_response_proto = out.File
	file_blobcast_rollupapis_v1_subscribe_to_headers_response_proto_goTypes = nil
	file_blobcast_rollupapis_v1_subscribe_to_headers_response_proto_depIdxs = nil
}
