// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: blobcast/storage/v1/chunk_data.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChunkData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ChunkData     []byte                 `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkData) Reset() {
	*x = ChunkData{}
	mi := &file_blobcast_storage_v1_chunk_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkData) ProtoMessage() {}

func (x *ChunkData) ProtoReflect() protoreflect.Message {
	mi := &file_blobcast_storage_v1_chunk_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkData.ProtoReflect.Descriptor instead.
func (*ChunkData) Descriptor() ([]byte, []int) {
	return file_blobcast_storage_v1_chunk_data_proto_rawDescGZIP(), []int{0}
}

func (x *ChunkData) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ChunkData) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

var File_blobcast_storage_v1_chunk_data_proto protoreflect.FileDescriptor

const file_blobcast_storage_v1_chunk_data_proto_rawDesc = "" +
	"\n" +
	"$blobcast/storage/v1/chunk_data.proto\x12\x13blobcast.storage.v1\"D\n" +
	"\tChunkData\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fR\tchunkDataB=Z;github.com/forma-dev/blobcast/pkg/proto/blobcast/storage/v1b\x06proto3"

var (
	file_blobcast_storage_v1_chunk_data_proto_rawDescOnce sync.Once
	file_blobcast_storage_v1_chunk_data_proto_rawDescData []byte
)

func file_blobcast_storage_v1_chunk_data_proto_rawDescGZIP() []byte {
	file_blobcast_storage_v1_chunk_data_proto_rawDescOnce.Do(func() {
		file_blobcast_storage_v1_chunk_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blobcast_storage_v1_chunk_data_proto_rawDesc), len(file_blobcast_storage_v1_chunk_data_proto_rawDesc)))
	})
	return file_blobcast_storage_v1_chunk_data_proto_rawDescData
}

var file_blobcast_storage_v1_chunk_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_blobcast_storage_v1_chunk_data_proto_goTypes = []any{
	(*ChunkData)(nil), // 0: blobcast.storage.v1.ChunkData
}
var file_blobcast_storage_v1_chunk_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blobcast_storage_v1_chunk_data_proto_init() }
func file_blobcast_storage_v1_chunk_data_proto_init() {
	if File_blobcast_storage_v1_chunk_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blobcast_storage_v1_chunk_data_proto_rawDesc), len(file_blobcast_storage_v1_chunk_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blobcast_storage_v1_chunk_data_proto_goTypes,
		DependencyIndexes: file_blobcast_storage_v1_chunk_data_proto_depIdxs,
		MessageInfos:      file_blobcast_storage_v1_chunk_data_proto_msgTypes,
	}.Build()
	File_blobcast_storage_v1_chunk_data_proto = out.File
	file_blobcast_storage_v1_chunk_data_proto_goTypes = nil
	file_blobcast_storage_v1_chunk_data_proto_depIdxs = nil
}
