// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: blobcast/storage/v1/compression_algorithm.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompressionAlgorithm int32

const (
	CompressionAlgorithm_COMPRESSION_ALGORITHM_UNSPECIFIED CompressionAlgorithm = 0
	CompressionAlgorithm_COMPRESSION_ALGORITHM_NONE        CompressionAlgorithm = 1 // Future compression algorithms can be added here
)

// Enum value maps for CompressionAlgorithm.
var (
	CompressionAlgorithm_name = map[int32]string{
		0: "COMPRESSION_ALGORITHM_UNSPECIFIED",
		1: "COMPRESSION_ALGORITHM_NONE",
	}
	CompressionAlgorithm_value = map[string]int32{
		"COMPRESSION_ALGORITHM_UNSPECIFIED": 0,
		"COMPRESSION_ALGORITHM_NONE":        1,
	}
)

func (x CompressionAlgorithm) Enum() *CompressionAlgorithm {
	p := new(CompressionAlgorithm)
	*p = x
	return p
}

func (x CompressionAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompressionAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_blobcast_storage_v1_compression_algorithm_proto_enumTypes[0].Descriptor()
}

func (CompressionAlgorithm) Type() protoreflect.EnumType {
	return &file_blobcast_storage_v1_compression_algorithm_proto_enumTypes[0]
}

func (x CompressionAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompressionAlgorithm.Descriptor instead.
func (CompressionAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_blobcast_storage_v1_compression_algorithm_proto_rawDescGZIP(), []int{0}
}

var File_blobcast_storage_v1_compression_algorithm_proto protoreflect.FileDescriptor

const file_blobcast_storage_v1_compression_algorithm_proto_rawDesc = "" +
	"\n" +
	"/blobcast/storage/v1/compression_algorithm.proto\x12\x13blobcast.storage.v1*]\n" +
	"\x14CompressionAlgorithm\x12%\n" +
	"!COMPRESSION_ALGORITHM_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCOMPRESSION_ALGORITHM_NONE\x10\x01B=Z;github.com/forma-dev/blobcast/pkg/proto/blobcast/storage/v1b\x06proto3"

var (
	file_blobcast_storage_v1_compression_algorithm_proto_rawDescOnce sync.Once
	file_blobcast_storage_v1_compression_algorithm_proto_rawDescData []byte
)

func file_blobcast_storage_v1_compression_algorithm_proto_rawDescGZIP() []byte {
	file_blobcast_storage_v1_compression_algorithm_proto_rawDescOnce.Do(func() {
		file_blobcast_storage_v1_compression_algorithm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blobcast_storage_v1_compression_algorithm_proto_rawDesc), len(file_blobcast_storage_v1_compression_algorithm_proto_rawDesc)))
	})
	return file_blobcast_storage_v1_compression_algorithm_proto_rawDescData
}

var file_blobcast_storage_v1_compression_algorithm_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_blobcast_storage_v1_compression_algorithm_proto_goTypes = []any{
	(CompressionAlgorithm)(0), // 0: blobcast.storage.v1.CompressionAlgorithm
}
var file_blobcast_storage_v1_compression_algorithm_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blobcast_storage_v1_compression_algorithm_proto_init() }
func file_blobcast_storage_v1_compression_algorithm_proto_init() {
	if File_blobcast_storage_v1_compression_algorithm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blobcast_storage_v1_compression_algorithm_proto_rawDesc), len(file_blobcast_storage_v1_compression_algorithm_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blobcast_storage_v1_compression_algorithm_proto_goTypes,
		DependencyIndexes: file_blobcast_storage_v1_compression_algorithm_proto_depIdxs,
		EnumInfos:         file_blobcast_storage_v1_compression_algorithm_proto_enumTypes,
	}.Build()
	File_blobcast_storage_v1_compression_algorithm_proto = out.File
	file_blobcast_storage_v1_compression_algorithm_proto_goTypes = nil
	file_blobcast_storage_v1_compression_algorithm_proto_depIdxs = nil
}
