// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: blobcast/storage/v1/file_reference.proto

package v1

import (
	v1 "github.com/forma-dev/blobcast/pkg/proto/blobcast/primitives/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a file within the directory structure
// references the file manifest blob
type FileReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *v1.BlobIdentifier     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RelativePath  string                 `protobuf:"bytes,2,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileReference) Reset() {
	*x = FileReference{}
	mi := &file_blobcast_storage_v1_file_reference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReference) ProtoMessage() {}

func (x *FileReference) ProtoReflect() protoreflect.Message {
	mi := &file_blobcast_storage_v1_file_reference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReference.ProtoReflect.Descriptor instead.
func (*FileReference) Descriptor() ([]byte, []int) {
	return file_blobcast_storage_v1_file_reference_proto_rawDescGZIP(), []int{0}
}

func (x *FileReference) GetId() *v1.BlobIdentifier {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *FileReference) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

var File_blobcast_storage_v1_file_reference_proto protoreflect.FileDescriptor

const file_blobcast_storage_v1_file_reference_proto_rawDesc = "" +
	"\n" +
	"(blobcast/storage/v1/file_reference.proto\x12\x13blobcast.storage.v1\x1a,blobcast/primitives/v1/blob_identifier.proto\"l\n" +
	"\rFileReference\x126\n" +
	"\x02id\x18\x01 \x01(\v2&.blobcast.primitives.v1.BlobIdentifierR\x02id\x12#\n" +
	"\rrelative_path\x18\x02 \x01(\tR\frelativePathB=Z;github.com/forma-dev/blobcast/pkg/proto/blobcast/storage/v1b\x06proto3"

var (
	file_blobcast_storage_v1_file_reference_proto_rawDescOnce sync.Once
	file_blobcast_storage_v1_file_reference_proto_rawDescData []byte
)

func file_blobcast_storage_v1_file_reference_proto_rawDescGZIP() []byte {
	file_blobcast_storage_v1_file_reference_proto_rawDescOnce.Do(func() {
		file_blobcast_storage_v1_file_reference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blobcast_storage_v1_file_reference_proto_rawDesc), len(file_blobcast_storage_v1_file_reference_proto_rawDesc)))
	})
	return file_blobcast_storage_v1_file_reference_proto_rawDescData
}

var file_blobcast_storage_v1_file_reference_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_blobcast_storage_v1_file_reference_proto_goTypes = []any{
	(*FileReference)(nil),     // 0: blobcast.storage.v1.FileReference
	(*v1.BlobIdentifier)(nil), // 1: blobcast.primitives.v1.BlobIdentifier
}
var file_blobcast_storage_v1_file_reference_proto_depIdxs = []int32{
	1, // 0: blobcast.storage.v1.FileReference.id:type_name -> blobcast.primitives.v1.BlobIdentifier
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_blobcast_storage_v1_file_reference_proto_init() }
func file_blobcast_storage_v1_file_reference_proto_init() {
	if File_blobcast_storage_v1_file_reference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blobcast_storage_v1_file_reference_proto_rawDesc), len(file_blobcast_storage_v1_file_reference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blobcast_storage_v1_file_reference_proto_goTypes,
		DependencyIndexes: file_blobcast_storage_v1_file_reference_proto_depIdxs,
		MessageInfos:      file_blobcast_storage_v1_file_reference_proto_msgTypes,
	}.Build()
	File_blobcast_storage_v1_file_reference_proto = out.File
	file_blobcast_storage_v1_file_reference_proto_goTypes = nil
	file_blobcast_storage_v1_file_reference_proto_depIdxs = nil
}
