// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: blobcast/primitives/v1/blob_identifier.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlobIdentifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Commitment    []byte                 `protobuf:"bytes,2,opt,name=commitment,proto3" json:"commitment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobIdentifier) Reset() {
	*x = BlobIdentifier{}
	mi := &file_blobcast_primitives_v1_blob_identifier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobIdentifier) ProtoMessage() {}

func (x *BlobIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_blobcast_primitives_v1_blob_identifier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobIdentifier.ProtoReflect.Descriptor instead.
func (*BlobIdentifier) Descriptor() ([]byte, []int) {
	return file_blobcast_primitives_v1_blob_identifier_proto_rawDescGZIP(), []int{0}
}

func (x *BlobIdentifier) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlobIdentifier) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

var File_blobcast_primitives_v1_blob_identifier_proto protoreflect.FileDescriptor

const file_blobcast_primitives_v1_blob_identifier_proto_rawDesc = "" +
	"\n" +
	",blobcast/primitives/v1/blob_identifier.proto\x12\x16blobcast.primitives.v1\"H\n" +
	"\x0eBlobIdentifier\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x1e\n" +
	"\n" +
	"commitment\x18\x02 \x01(\fR\n" +
	"commitmentB@Z>github.com/forma-dev/blobcast/pkg/proto/blobcast/primitives/v1b\x06proto3"

var (
	file_blobcast_primitives_v1_blob_identifier_proto_rawDescOnce sync.Once
	file_blobcast_primitives_v1_blob_identifier_proto_rawDescData []byte
)

func file_blobcast_primitives_v1_blob_identifier_proto_rawDescGZIP() []byte {
	file_blobcast_primitives_v1_blob_identifier_proto_rawDescOnce.Do(func() {
		file_blobcast_primitives_v1_blob_identifier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blobcast_primitives_v1_blob_identifier_proto_rawDesc), len(file_blobcast_primitives_v1_blob_identifier_proto_rawDesc)))
	})
	return file_blobcast_primitives_v1_blob_identifier_proto_rawDescData
}

var file_blobcast_primitives_v1_blob_identifier_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_blobcast_primitives_v1_blob_identifier_proto_goTypes = []any{
	(*BlobIdentifier)(nil), // 0: blobcast.primitives.v1.BlobIdentifier
}
var file_blobcast_primitives_v1_blob_identifier_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blobcast_primitives_v1_blob_identifier_proto_init() }
func file_blobcast_primitives_v1_blob_identifier_proto_init() {
	if File_blobcast_primitives_v1_blob_identifier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blobcast_primitives_v1_blob_identifier_proto_rawDesc), len(file_blobcast_primitives_v1_blob_identifier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blobcast_primitives_v1_blob_identifier_proto_goTypes,
		DependencyIndexes: file_blobcast_primitives_v1_blob_identifier_proto_depIdxs,
		MessageInfos:      file_blobcast_primitives_v1_blob_identifier_proto_msgTypes,
	}.Build()
	File_blobcast_primitives_v1_blob_identifier_proto = out.File
	file_blobcast_primitives_v1_blob_identifier_proto_goTypes = nil
	file_blobcast_primitives_v1_blob_identifier_proto_depIdxs = nil
}
