// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: blobcast/syncapis/v1/chunk_with_hash.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChunkWithHash struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkData     []byte                 `protobuf:"bytes,1,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`
	ChunkHash     []byte                 `protobuf:"bytes,2,opt,name=chunk_hash,json=chunkHash,proto3" json:"chunk_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkWithHash) Reset() {
	*x = ChunkWithHash{}
	mi := &file_blobcast_syncapis_v1_chunk_with_hash_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkWithHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkWithHash) ProtoMessage() {}

func (x *ChunkWithHash) ProtoReflect() protoreflect.Message {
	mi := &file_blobcast_syncapis_v1_chunk_with_hash_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkWithHash.ProtoReflect.Descriptor instead.
func (*ChunkWithHash) Descriptor() ([]byte, []int) {
	return file_blobcast_syncapis_v1_chunk_with_hash_proto_rawDescGZIP(), []int{0}
}

func (x *ChunkWithHash) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

func (x *ChunkWithHash) GetChunkHash() []byte {
	if x != nil {
		return x.ChunkHash
	}
	return nil
}

var File_blobcast_syncapis_v1_chunk_with_hash_proto protoreflect.FileDescriptor

const file_blobcast_syncapis_v1_chunk_with_hash_proto_rawDesc = "" +
	"\n" +
	"*blobcast/syncapis/v1/chunk_with_hash.proto\x12\x14blobcast.syncapis.v1\"M\n" +
	"\rChunkWithHash\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\x01 \x01(\fR\tchunkData\x12\x1d\n" +
	"\n" +
	"chunk_hash\x18\x02 \x01(\fR\tchunkHashB>Z<github.com/forma-dev/blobcast/pkg/proto/blobcast/syncapis/v1b\x06proto3"

var (
	file_blobcast_syncapis_v1_chunk_with_hash_proto_rawDescOnce sync.Once
	file_blobcast_syncapis_v1_chunk_with_hash_proto_rawDescData []byte
)

func file_blobcast_syncapis_v1_chunk_with_hash_proto_rawDescGZIP() []byte {
	file_blobcast_syncapis_v1_chunk_with_hash_proto_rawDescOnce.Do(func() {
		file_blobcast_syncapis_v1_chunk_with_hash_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blobcast_syncapis_v1_chunk_with_hash_proto_rawDesc), len(file_blobcast_syncapis_v1_chunk_with_hash_proto_rawDesc)))
	})
	return file_blobcast_syncapis_v1_chunk_with_hash_proto_rawDescData
}

var file_blobcast_syncapis_v1_chunk_with_hash_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_blobcast_syncapis_v1_chunk_with_hash_proto_goTypes = []any{
	(*ChunkWithHash)(nil), // 0: blobcast.syncapis.v1.ChunkWithHash
}
var file_blobcast_syncapis_v1_chunk_with_hash_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blobcast_syncapis_v1_chunk_with_hash_proto_init() }
func file_blobcast_syncapis_v1_chunk_with_hash_proto_init() {
	if File_blobcast_syncapis_v1_chunk_with_hash_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blobcast_syncapis_v1_chunk_with_hash_proto_rawDesc), len(file_blobcast_syncapis_v1_chunk_with_hash_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blobcast_syncapis_v1_chunk_with_hash_proto_goTypes,
		DependencyIndexes: file_blobcast_syncapis_v1_chunk_with_hash_proto_depIdxs,
		MessageInfos:      file_blobcast_syncapis_v1_chunk_with_hash_proto_msgTypes,
	}.Build()
	File_blobcast_syncapis_v1_chunk_with_hash_proto = out.File
	file_blobcast_syncapis_v1_chunk_with_hash_proto_goTypes = nil
	file_blobcast_syncapis_v1_chunk_with_hash_proto_depIdxs = nil
}
