// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: blobcast/syncapis/v1/stream_blocks_request.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamBlocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartHeight   uint64                 `protobuf:"varint,1,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	EndHeight     uint64                 `protobuf:"varint,2,opt,name=end_height,json=endHeight,proto3" json:"end_height,omitempty"`
	BatchSize     uint32                 `protobuf:"varint,3,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamBlocksRequest) Reset() {
	*x = StreamBlocksRequest{}
	mi := &file_blobcast_syncapis_v1_stream_blocks_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamBlocksRequest) ProtoMessage() {}

func (x *StreamBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blobcast_syncapis_v1_stream_blocks_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamBlocksRequest.ProtoReflect.Descriptor instead.
func (*StreamBlocksRequest) Descriptor() ([]byte, []int) {
	return file_blobcast_syncapis_v1_stream_blocks_request_proto_rawDescGZIP(), []int{0}
}

func (x *StreamBlocksRequest) GetStartHeight() uint64 {
	if x != nil {
		return x.StartHeight
	}
	return 0
}

func (x *StreamBlocksRequest) GetEndHeight() uint64 {
	if x != nil {
		return x.EndHeight
	}
	return 0
}

func (x *StreamBlocksRequest) GetBatchSize() uint32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

var File_blobcast_syncapis_v1_stream_blocks_request_proto protoreflect.FileDescriptor

const file_blobcast_syncapis_v1_stream_blocks_request_proto_rawDesc = "" +
	"\n" +
	"0blobcast/syncapis/v1/stream_blocks_request.proto\x12\x14blobcast.syncapis.v1\x1a\x1fgoogle/api/field_behavior.proto\"\x80\x01\n" +
	"\x13StreamBlocksRequest\x12&\n" +
	"\fstart_height\x18\x01 \x01(\x04B\x03\xe0A\x02R\vstartHeight\x12\"\n" +
	"\n" +
	"end_height\x18\x02 \x01(\x04B\x03\xe0A\x02R\tendHeight\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x03 \x01(\rR\tbatchSizeB>Z<github.com/forma-dev/blobcast/pkg/proto/blobcast/syncapis/v1b\x06proto3"

var (
	file_blobcast_syncapis_v1_stream_blocks_request_proto_rawDescOnce sync.Once
	file_blobcast_syncapis_v1_stream_blocks_request_proto_rawDescData []byte
)

func file_blobcast_syncapis_v1_stream_blocks_request_proto_rawDescGZIP() []byte {
	file_blobcast_syncapis_v1_stream_blocks_request_proto_rawDescOnce.Do(func() {
		file_blobcast_syncapis_v1_stream_blocks_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blobcast_syncapis_v1_stream_blocks_request_proto_rawDesc), len(file_blobcast_syncapis_v1_stream_blocks_request_proto_rawDesc)))
	})
	return file_blobcast_syncapis_v1_stream_blocks_request_proto_rawDescData
}

var file_blobcast_syncapis_v1_stream_blocks_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_blobcast_syncapis_v1_stream_blocks_request_proto_goTypes = []any{
	(*StreamBlocksRequest)(nil), // 0: blobcast.syncapis.v1.StreamBlocksRequest
}
var file_blobcast_syncapis_v1_stream_blocks_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blobcast_syncapis_v1_stream_blocks_request_proto_init() }
func file_blobcast_syncapis_v1_stream_blocks_request_proto_init() {
	if File_blobcast_syncapis_v1_stream_blocks_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blobcast_syncapis_v1_stream_blocks_request_proto_rawDesc), len(file_blobcast_syncapis_v1_stream_blocks_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blobcast_syncapis_v1_stream_blocks_request_proto_goTypes,
		DependencyIndexes: file_blobcast_syncapis_v1_stream_blocks_request_proto_depIdxs,
		MessageInfos:      file_blobcast_syncapis_v1_stream_blocks_request_proto_msgTypes,
	}.Build()
	File_blobcast_syncapis_v1_stream_blocks_request_proto = out.File
	file_blobcast_syncapis_v1_stream_blocks_request_proto_goTypes = nil
	file_blobcast_syncapis_v1_stream_blocks_request_proto_depIdxs = nil
}
