// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: blobcast/syncapis/v1/stream_blocks_response.proto

package v1

import (
	v1 "github.com/forma-dev/blobcast/pkg/proto/blobcast/rollup/v1"
	v11 "github.com/forma-dev/blobcast/pkg/proto/blobcast/storage/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamBlocksResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Block         *v1.Block                `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Chunks        []*ChunkWithHash         `protobuf:"bytes,2,rep,name=chunks,proto3" json:"chunks,omitempty"`
	Files         []*v11.FileManifest      `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	Dirs          []*v11.DirectoryManifest `protobuf:"bytes,4,rep,name=dirs,proto3" json:"dirs,omitempty"`
	MmrSnapshot   []byte                   `protobuf:"bytes,5,opt,name=mmr_snapshot,json=mmrSnapshot,proto3" json:"mmr_snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamBlocksResponse) Reset() {
	*x = StreamBlocksResponse{}
	mi := &file_blobcast_syncapis_v1_stream_blocks_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamBlocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamBlocksResponse) ProtoMessage() {}

func (x *StreamBlocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blobcast_syncapis_v1_stream_blocks_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamBlocksResponse.ProtoReflect.Descriptor instead.
func (*StreamBlocksResponse) Descriptor() ([]byte, []int) {
	return file_blobcast_syncapis_v1_stream_blocks_response_proto_rawDescGZIP(), []int{0}
}

func (x *StreamBlocksResponse) GetBlock() *v1.Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *StreamBlocksResponse) GetChunks() []*ChunkWithHash {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *StreamBlocksResponse) GetFiles() []*v11.FileManifest {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *StreamBlocksResponse) GetDirs() []*v11.DirectoryManifest {
	if x != nil {
		return x.Dirs
	}
	return nil
}

func (x *StreamBlocksResponse) GetMmrSnapshot() []byte {
	if x != nil {
		return x.MmrSnapshot
	}
	return nil
}

var File_blobcast_syncapis_v1_stream_blocks_response_proto protoreflect.FileDescriptor

const file_blobcast_syncapis_v1_stream_blocks_response_proto_rawDesc = "" +
	"\n" +
	"1blobcast/syncapis/v1/stream_blocks_response.proto\x12\x14blobcast.syncapis.v1\x1a\x1eblobcast/rollup/v1/block.proto\x1a'blobcast/storage/v1/file_manifest.proto\x1a,blobcast/storage/v1/directory_manifest.proto\x1a*blobcast/syncapis/v1/chunk_with_hash.proto\"\x9c\x02\n" +
	"\x14StreamBlocksResponse\x12/\n" +
	"\x05block\x18\x01 \x01(\v2\x19.blobcast.rollup.v1.BlockR\x05block\x12;\n" +
	"\x06chunks\x18\x02 \x03(\v2#.blobcast.syncapis.v1.ChunkWithHashR\x06chunks\x127\n" +
	"\x05files\x18\x03 \x03(\v2!.blobcast.storage.v1.FileManifestR\x05files\x12:\n" +
	"\x04dirs\x18\x04 \x03(\v2&.blobcast.storage.v1.DirectoryManifestR\x04dirs\x12!\n" +
	"\fmmr_snapshot\x18\x05 \x01(\fR\vmmrSnapshotB>Z<github.com/forma-dev/blobcast/pkg/proto/blobcast/syncapis/v1b\x06proto3"

var (
	file_blobcast_syncapis_v1_stream_blocks_response_proto_rawDescOnce sync.Once
	file_blobcast_syncapis_v1_stream_blocks_response_proto_rawDescData []byte
)

func file_blobcast_syncapis_v1_stream_blocks_response_proto_rawDescGZIP() []byte {
	file_blobcast_syncapis_v1_stream_blocks_response_proto_rawDescOnce.Do(func() {
		file_blobcast_syncapis_v1_stream_blocks_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blobcast_syncapis_v1_stream_blocks_response_proto_rawDesc), len(file_blobcast_syncapis_v1_stream_blocks_response_proto_rawDesc)))
	})
	return file_blobcast_syncapis_v1_stream_blocks_response_proto_rawDescData
}

var file_blobcast_syncapis_v1_stream_blocks_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_blobcast_syncapis_v1_stream_blocks_response_proto_goTypes = []any{
	(*StreamBlocksResponse)(nil),  // 0: blobcast.syncapis.v1.StreamBlocksResponse
	(*v1.Block)(nil),              // 1: blobcast.rollup.v1.Block
	(*ChunkWithHash)(nil),         // 2: blobcast.syncapis.v1.ChunkWithHash
	(*v11.FileManifest)(nil),      // 3: blobcast.storage.v1.FileManifest
	(*v11.DirectoryManifest)(nil), // 4: blobcast.storage.v1.DirectoryManifest
}
var file_blobcast_syncapis_v1_stream_blocks_response_proto_depIdxs = []int32{
	1, // 0: blobcast.syncapis.v1.StreamBlocksResponse.block:type_name -> blobcast.rollup.v1.Block
	2, // 1: blobcast.syncapis.v1.StreamBlocksResponse.chunks:type_name -> blobcast.syncapis.v1.ChunkWithHash
	3, // 2: blobcast.syncapis.v1.StreamBlocksResponse.files:type_name -> blobcast.storage.v1.FileManifest
	4, // 3: blobcast.syncapis.v1.StreamBlocksResponse.dirs:type_name -> blobcast.storage.v1.DirectoryManifest
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_blobcast_syncapis_v1_stream_blocks_response_proto_init() }
func file_blobcast_syncapis_v1_stream_blocks_response_proto_init() {
	if File_blobcast_syncapis_v1_stream_blocks_response_proto != nil {
		return
	}
	file_blobcast_syncapis_v1_chunk_with_hash_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blobcast_syncapis_v1_stream_blocks_response_proto_rawDesc), len(file_blobcast_syncapis_v1_stream_blocks_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blobcast_syncapis_v1_stream_blocks_response_proto_goTypes,
		DependencyIndexes: file_blobcast_syncapis_v1_stream_blocks_response_proto_depIdxs,
		MessageInfos:      file_blobcast_syncapis_v1_stream_blocks_response_proto_msgTypes,
	}.Build()
	File_blobcast_syncapis_v1_stream_blocks_response_proto = out.File
	file_blobcast_syncapis_v1_stream_blocks_response_proto_goTypes = nil
	file_blobcast_syncapis_v1_stream_blocks_response_proto_depIdxs = nil
}
