// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: blobcast/syncapis/v1/sync_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_blobcast_syncapis_v1_sync_service_proto protoreflect.FileDescriptor

const file_blobcast_syncapis_v1_sync_service_proto_rawDesc = "" +
	"\n" +
	"'blobcast/syncapis/v1/sync_service.proto\x12\x14blobcast.syncapis.v1\x1a0blobcast/syncapis/v1/stream_blocks_request.proto\x1a1blobcast/syncapis/v1/stream_blocks_response.proto2v\n" +
	"\vSyncService\x12g\n" +
	"\fStreamBlocks\x12).blobcast.syncapis.v1.StreamBlocksRequest\x1a*.blobcast.syncapis.v1.StreamBlocksResponse0\x01B>Z<github.com/forma-dev/blobcast/pkg/proto/blobcast/syncapis/v1b\x06proto3"

var file_blobcast_syncapis_v1_sync_service_proto_goTypes = []any{
	(*StreamBlocksRequest)(nil),  // 0: blobcast.syncapis.v1.StreamBlocksRequest
	(*StreamBlocksResponse)(nil), // 1: blobcast.syncapis.v1.StreamBlocksResponse
}
var file_blobcast_syncapis_v1_sync_service_proto_depIdxs = []int32{
	0, // 0: blobcast.syncapis.v1.SyncService.StreamBlocks:input_type -> blobcast.syncapis.v1.StreamBlocksRequest
	1, // 1: blobcast.syncapis.v1.SyncService.StreamBlocks:output_type -> blobcast.syncapis.v1.StreamBlocksResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blobcast_syncapis_v1_sync_service_proto_init() }
func file_blobcast_syncapis_v1_sync_service_proto_init() {
	if File_blobcast_syncapis_v1_sync_service_proto != nil {
		return
	}
	file_blobcast_syncapis_v1_stream_blocks_request_proto_init()
	file_blobcast_syncapis_v1_stream_blocks_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blobcast_syncapis_v1_sync_service_proto_rawDesc), len(file_blobcast_syncapis_v1_sync_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blobcast_syncapis_v1_sync_service_proto_goTypes,
		DependencyIndexes: file_blobcast_syncapis_v1_sync_service_proto_depIdxs,
	}.Build()
	File_blobcast_syncapis_v1_sync_service_proto = out.File
	file_blobcast_syncapis_v1_sync_service_proto_goTypes = nil
	file_blobcast_syncapis_v1_sync_service_proto_depIdxs = nil
}
