// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: blobcast/storageapis/v1/get_file_data_response.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFileDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileDataResponse) Reset() {
	*x = GetFileDataResponse{}
	mi := &file_blobcast_storageapis_v1_get_file_data_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileDataResponse) ProtoMessage() {}

func (x *GetFileDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blobcast_storageapis_v1_get_file_data_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileDataResponse.ProtoReflect.Descriptor instead.
func (*GetFileDataResponse) Descriptor() ([]byte, []int) {
	return file_blobcast_storageapis_v1_get_file_data_response_proto_rawDescGZIP(), []int{0}
}

func (x *GetFileDataResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_blobcast_storageapis_v1_get_file_data_response_proto protoreflect.FileDescriptor

const file_blobcast_storageapis_v1_get_file_data_response_proto_rawDesc = "" +
	"\n" +
	"4blobcast/storageapis/v1/get_file_data_response.proto\x12\x17blobcast.storageapis.v1\")\n" +
	"\x13GetFileDataResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04dataBAZ?github.com/forma-dev/blobcast/pkg/proto/blobcast/storageapis/v1b\x06proto3"

var (
	file_blobcast_storageapis_v1_get_file_data_response_proto_rawDescOnce sync.Once
	file_blobcast_storageapis_v1_get_file_data_response_proto_rawDescData []byte
)

func file_blobcast_storageapis_v1_get_file_data_response_proto_rawDescGZIP() []byte {
	file_blobcast_storageapis_v1_get_file_data_response_proto_rawDescOnce.Do(func() {
		file_blobcast_storageapis_v1_get_file_data_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blobcast_storageapis_v1_get_file_data_response_proto_rawDesc), len(file_blobcast_storageapis_v1_get_file_data_response_proto_rawDesc)))
	})
	return file_blobcast_storageapis_v1_get_file_data_response_proto_rawDescData
}

var file_blobcast_storageapis_v1_get_file_data_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_blobcast_storageapis_v1_get_file_data_response_proto_goTypes = []any{
	(*GetFileDataResponse)(nil), // 0: blobcast.storageapis.v1.GetFileDataResponse
}
var file_blobcast_storageapis_v1_get_file_data_response_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blobcast_storageapis_v1_get_file_data_response_proto_init() }
func file_blobcast_storageapis_v1_get_file_data_response_proto_init() {
	if File_blobcast_storageapis_v1_get_file_data_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blobcast_storageapis_v1_get_file_data_response_proto_rawDesc), len(file_blobcast_storageapis_v1_get_file_data_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blobcast_storageapis_v1_get_file_data_response_proto_goTypes,
		DependencyIndexes: file_blobcast_storageapis_v1_get_file_data_response_proto_depIdxs,
		MessageInfos:      file_blobcast_storageapis_v1_get_file_data_response_proto_msgTypes,
	}.Build()
	File_blobcast_storageapis_v1_get_file_data_response_proto = out.File
	file_blobcast_storageapis_v1_get_file_data_response_proto_goTypes = nil
	file_blobcast_storageapis_v1_get_file_data_response_proto_depIdxs = nil
}
