// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: blobcast/storageapis/v1/get_file_manifest_response.proto

package v1

import (
	v1 "github.com/forma-dev/blobcast/pkg/proto/blobcast/primitives/v1"
	v11 "github.com/forma-dev/blobcast/pkg/proto/blobcast/storage/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFileManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *v1.BlobIdentifier     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Manifest      *v11.FileManifest      `protobuf:"bytes,2,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileManifestResponse) Reset() {
	*x = GetFileManifestResponse{}
	mi := &file_blobcast_storageapis_v1_get_file_manifest_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileManifestResponse) ProtoMessage() {}

func (x *GetFileManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blobcast_storageapis_v1_get_file_manifest_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileManifestResponse.ProtoReflect.Descriptor instead.
func (*GetFileManifestResponse) Descriptor() ([]byte, []int) {
	return file_blobcast_storageapis_v1_get_file_manifest_response_proto_rawDescGZIP(), []int{0}
}

func (x *GetFileManifestResponse) GetId() *v1.BlobIdentifier {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *GetFileManifestResponse) GetManifest() *v11.FileManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

var File_blobcast_storageapis_v1_get_file_manifest_response_proto protoreflect.FileDescriptor

const file_blobcast_storageapis_v1_get_file_manifest_response_proto_rawDesc = "" +
	"\n" +
	"8blobcast/storageapis/v1/get_file_manifest_response.proto\x12\x17blobcast.storageapis.v1\x1a,blobcast/primitives/v1/blob_identifier.proto\x1a'blobcast/storage/v1/file_manifest.proto\"\x90\x01\n" +
	"\x17GetFileManifestResponse\x126\n" +
	"\x02id\x18\x01 \x01(\v2&.blobcast.primitives.v1.BlobIdentifierR\x02id\x12=\n" +
	"\bmanifest\x18\x02 \x01(\v2!.blobcast.storage.v1.FileManifestR\bmanifestBAZ?github.com/forma-dev/blobcast/pkg/proto/blobcast/storageapis/v1b\x06proto3"

var (
	file_blobcast_storageapis_v1_get_file_manifest_response_proto_rawDescOnce sync.Once
	file_blobcast_storageapis_v1_get_file_manifest_response_proto_rawDescData []byte
)

func file_blobcast_storageapis_v1_get_file_manifest_response_proto_rawDescGZIP() []byte {
	file_blobcast_storageapis_v1_get_file_manifest_response_proto_rawDescOnce.Do(func() {
		file_blobcast_storageapis_v1_get_file_manifest_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blobcast_storageapis_v1_get_file_manifest_response_proto_rawDesc), len(file_blobcast_storageapis_v1_get_file_manifest_response_proto_rawDesc)))
	})
	return file_blobcast_storageapis_v1_get_file_manifest_response_proto_rawDescData
}

var file_blobcast_storageapis_v1_get_file_manifest_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_blobcast_storageapis_v1_get_file_manifest_response_proto_goTypes = []any{
	(*GetFileManifestResponse)(nil), // 0: blobcast.storageapis.v1.GetFileManifestResponse
	(*v1.BlobIdentifier)(nil),       // 1: blobcast.primitives.v1.BlobIdentifier
	(*v11.FileManifest)(nil),        // 2: blobcast.storage.v1.FileManifest
}
var file_blobcast_storageapis_v1_get_file_manifest_response_proto_depIdxs = []int32{
	1, // 0: blobcast.storageapis.v1.GetFileManifestResponse.id:type_name -> blobcast.primitives.v1.BlobIdentifier
	2, // 1: blobcast.storageapis.v1.GetFileManifestResponse.manifest:type_name -> blobcast.storage.v1.FileManifest
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_blobcast_storageapis_v1_get_file_manifest_response_proto_init() }
func file_blobcast_storageapis_v1_get_file_manifest_response_proto_init() {
	if File_blobcast_storageapis_v1_get_file_manifest_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blobcast_storageapis_v1_get_file_manifest_response_proto_rawDesc), len(file_blobcast_storageapis_v1_get_file_manifest_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blobcast_storageapis_v1_get_file_manifest_response_proto_goTypes,
		DependencyIndexes: file_blobcast_storageapis_v1_get_file_manifest_response_proto_depIdxs,
		MessageInfos:      file_blobcast_storageapis_v1_get_file_manifest_response_proto_msgTypes,
	}.Build()
	File_blobcast_storageapis_v1_get_file_manifest_response_proto = out.File
	file_blobcast_storageapis_v1_get_file_manifest_response_proto_goTypes = nil
	file_blobcast_storageapis_v1_get_file_manifest_response_proto_depIdxs = nil
}
