// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: blobcast/storageapis/v1/storage_service.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_blobcast_storageapis_v1_storage_service_proto protoreflect.FileDescriptor

const file_blobcast_storageapis_v1_storage_service_proto_rawDesc = "" +
	"\n" +
	"-blobcast/storageapis/v1/storage_service.proto\x12\x17blobcast.storageapis.v1\x1a<blobcast/storageapis/v1/get_directory_manifest_request.proto\x1a=blobcast/storageapis/v1/get_directory_manifest_response.proto\x1a7blobcast/storageapis/v1/get_file_manifest_request.proto\x1a8blobcast/storageapis/v1/get_file_manifest_response.proto\x1a3blobcast/storageapis/v1/get_file_data_request.proto\x1a4blobcast/storageapis/v1/get_file_data_response.proto\x1a\x1cgoogle/api/annotations.proto2\xdf\x03\n" +
	"\x0eStorageService\x12\xa7\x01\n" +
	"\x14GetDirectoryManifest\x124.blobcast.storageapis.v1.GetDirectoryManifestRequest\x1a5.blobcast.storageapis.v1.GetDirectoryManifestResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/storage/directory/{id}\x12\x93\x01\n" +
	"\x0fGetFileManifest\x12/.blobcast.storageapis.v1.GetFileManifestRequest\x1a0.blobcast.storageapis.v1.GetFileManifestResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/storage/file/{id}\x12\x8c\x01\n" +
	"\vGetFileData\x12+.blobcast.storageapis.v1.GetFileDataRequest\x1a,.blobcast.storageapis.v1.GetFileDataResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/storage/file/{id}/dataBAZ?github.com/forma-dev/blobcast/pkg/proto/blobcast/storageapis/v1b\x06proto3"

var file_blobcast_storageapis_v1_storage_service_proto_goTypes = []any{
	(*GetDirectoryManifestRequest)(nil),  // 0: blobcast.storageapis.v1.GetDirectoryManifestRequest
	(*GetFileManifestRequest)(nil),       // 1: blobcast.storageapis.v1.GetFileManifestRequest
	(*GetFileDataRequest)(nil),           // 2: blobcast.storageapis.v1.GetFileDataRequest
	(*GetDirectoryManifestResponse)(nil), // 3: blobcast.storageapis.v1.GetDirectoryManifestResponse
	(*GetFileManifestResponse)(nil),      // 4: blobcast.storageapis.v1.GetFileManifestResponse
	(*GetFileDataResponse)(nil),          // 5: blobcast.storageapis.v1.GetFileDataResponse
}
var file_blobcast_storageapis_v1_storage_service_proto_depIdxs = []int32{
	0, // 0: blobcast.storageapis.v1.StorageService.GetDirectoryManifest:input_type -> blobcast.storageapis.v1.GetDirectoryManifestRequest
	1, // 1: blobcast.storageapis.v1.StorageService.GetFileManifest:input_type -> blobcast.storageapis.v1.GetFileManifestRequest
	2, // 2: blobcast.storageapis.v1.StorageService.GetFileData:input_type -> blobcast.storageapis.v1.GetFileDataRequest
	3, // 3: blobcast.storageapis.v1.StorageService.GetDirectoryManifest:output_type -> blobcast.storageapis.v1.GetDirectoryManifestResponse
	4, // 4: blobcast.storageapis.v1.StorageService.GetFileManifest:output_type -> blobcast.storageapis.v1.GetFileManifestResponse
	5, // 5: blobcast.storageapis.v1.StorageService.GetFileData:output_type -> blobcast.storageapis.v1.GetFileDataResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blobcast_storageapis_v1_storage_service_proto_init() }
func file_blobcast_storageapis_v1_storage_service_proto_init() {
	if File_blobcast_storageapis_v1_storage_service_proto != nil {
		return
	}
	file_blobcast_storageapis_v1_get_directory_manifest_request_proto_init()
	file_blobcast_storageapis_v1_get_directory_manifest_response_proto_init()
	file_blobcast_storageapis_v1_get_file_manifest_request_proto_init()
	file_blobcast_storageapis_v1_get_file_manifest_response_proto_init()
	file_blobcast_storageapis_v1_get_file_data_request_proto_init()
	file_blobcast_storageapis_v1_get_file_data_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blobcast_storageapis_v1_storage_service_proto_rawDesc), len(file_blobcast_storageapis_v1_storage_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blobcast_storageapis_v1_storage_service_proto_goTypes,
		DependencyIndexes: file_blobcast_storageapis_v1_storage_service_proto_depIdxs,
	}.Build()
	File_blobcast_storageapis_v1_storage_service_proto = out.File
	file_blobcast_storageapis_v1_storage_service_proto_goTypes = nil
	file_blobcast_storageapis_v1_storage_service_proto_depIdxs = nil
}
